{
  "dependencies": [
    {
      "name": "fastapi",
      "version": "0.104.1",
      "vulns": [
        {
          "aliases": [
            "CVE-2024-24762",
            "GHSA-2jv5-9r88-3w3p",
            "GHSA-qf9m-vfgh-m389"
          ],
          "description": "FastAPI is a web framework for building APIs with Python 3.8+ based on standard Python type hints. When using form data, `python-multipart` uses a Regular Expression to parse the HTTP `Content-Type` header, including options. An attacker could send a custom-made `Content-Type` option that is very difficult for the RegEx to process, consuming CPU resources and stalling indefinitely (minutes or more) while holding the main event loop. This means that process can't handle any more requests. It's a ReDoS(Regular expression Denial of Service), it only applies to those reading form data, using `python-multipart`. This vulnerability has been patched in version 0.109.1.",
          "ecosystem": "python",
          "fix_versions": [
            "0.109.1",
            "9d34ad0ee8a0dfbbcce06f76c2d5d851085024fc"
          ],
          "id": "PYSEC-2024-38",
          "package": "fastapi",
          "references": [
            "https://github.com/tiangolo/fastapi/security/advisories/GHSA-qf9m-vfgh-m389",
            "https://github.com/tiangolo/fastapi/commit/9d34ad0ee8a0dfbbcce06f76c2d5d851085024fc",
            "https://github.com/tiangolo/fastapi/releases/tag/0.109.1"
          ],
          "severity": "unknown",
          "source_id": "PYSEC-2024-38",
          "version": "0.104.1"
        }
      ]
    },
    {
      "name": "uvicorn",
      "version": "0.24.0",
      "vulns": []
    },
    {
      "name": "pydantic",
      "version": "2.5.0",
      "vulns": []
    },
    {
      "name": "httpx",
      "version": "0.25.2",
      "vulns": []
    },
    {
      "name": "aiofiles",
      "version": "23.2.1",
      "vulns": []
    },
    {
      "name": "python-multipart",
      "version": "0.0.6",
      "vulns": [
        {
          "aliases": [
            "CVE-2024-24762",
            "GHSA-qf9m-vfgh-m389",
            "PYSEC-2024-38"
          ],
          "description": "python-multipart vulnerable to Content-Type Header ReDoS",
          "ecosystem": "python",
          "fix_versions": [
            "0.0.7"
          ],
          "id": "GHSA-2jv5-9r88-3w3p",
          "package": "python-multipart",
          "references": [
            "https://github.com/Kludex/python-multipart/security/advisories/GHSA-2jv5-9r88-3w3p",
            "https://nvd.nist.gov/vuln/detail/CVE-2024-24762",
            "https://github.com/github/advisory-database/pull/4829",
            "https://github.com/Kludex/python-multipart/commit/20f0ef6b4e4caf7d69a667c54dff57fe467109a4",
            "https://github.com/encode/starlette/commit/13e5c26a27f4903924624736abd6131b2da80cc5",
            "https://github.com/tiangolo/fastapi/commit/9d34ad0ee8a0dfbbcce06f76c2d5d851085024fc",
            "https://github.com/Kludex/python-multipart",
            "https://github.com/andrew-d/python-multipart/blob/d3d16dae4b061c34fe9d3c9081d9800c49fc1f7a/multipart/multipart.py#L72-L74",
            "https://github.com/pypa/advisory-database/tree/main/vulns/fastapi/PYSEC-2024-38.yaml",
            "https://github.com/tiangolo/fastapi/releases/tag/0.109.1"
          ],
          "severity": "high",
          "source_id": "GHSA-2jv5-9r88-3w3p",
          "version": "0.0.6"
        },
        {
          "aliases": [
            "CVE-2024-53981"
          ],
          "description": "Denial of service (DoS) via deformation `multipart/form-data` boundary",
          "ecosystem": "python",
          "fix_versions": [
            "0.0.18"
          ],
          "id": "GHSA-59g5-xgcq-4qw3",
          "package": "python-multipart",
          "references": [
            "https://github.com/Kludex/python-multipart/security/advisories/GHSA-59g5-xgcq-4qw3",
            "https://nvd.nist.gov/vuln/detail/CVE-2024-53981",
            "https://github.com/Kludex/python-multipart/commit/c4fe4d3cebc08c660e57dd709af1ffa7059b3177",
            "https://github.com/Kludex/python-multipart"
          ],
          "severity": "high",
          "source_id": "GHSA-59g5-xgcq-4qw3",
          "version": "0.0.6"
        }
      ]
    },
    {
      "name": "pysocks",
      "version": "1.7.1",
      "vulns": []
    },
    {
      "name": "stem",
      "version": "1.8.2",
      "vulns": []
    },
    {
      "name": "requests",
      "version": "2.31.0",
      "vulns": [
        {
          "aliases": [
            "CVE-2024-47081"
          ],
          "description": "Requests vulnerable to .netrc credentials leak via malicious URLs",
          "ecosystem": "python",
          "fix_versions": [
            "2.32.4"
          ],
          "id": "GHSA-9hjg-9r4m-mvj7",
          "package": "requests",
          "references": [
            "https://github.com/psf/requests/security/advisories/GHSA-9hjg-9r4m-mvj7",
            "https://nvd.nist.gov/vuln/detail/CVE-2024-47081",
            "https://github.com/psf/requests/pull/6965",
            "https://github.com/psf/requests/commit/96ba401c1296ab1dda74a2365ef36d88f7d144ef",
            "https://github.com/psf/requests",
            "https://requests.readthedocs.io/en/latest/api/#requests.Session.trust_env",
            "https://seclists.org/fulldisclosure/2025/Jun/2",
            "http://seclists.org/fulldisclosure/2025/Jun/2",
            "http://www.openwall.com/lists/oss-security/2025/06/03/11",
            "http://www.openwall.com/lists/oss-security/2025/06/03/9",
            "http://www.openwall.com/lists/oss-security/2025/06/04/1",
            "http://www.openwall.com/lists/oss-security/2025/06/04/6"
          ],
          "severity": "medium",
          "source_id": "GHSA-9hjg-9r4m-mvj7",
          "version": "2.31.0"
        },
        {
          "aliases": [
            "CVE-2024-35195"
          ],
          "description": "Requests `Session` object does not verify requests after making first request with verify=False",
          "ecosystem": "python",
          "fix_versions": [
            "2.32.0"
          ],
          "id": "GHSA-9wx4-h78v-vm56",
          "package": "requests",
          "references": [
            "https://github.com/psf/requests/security/advisories/GHSA-9wx4-h78v-vm56",
            "https://nvd.nist.gov/vuln/detail/CVE-2024-35195",
            "https://github.com/psf/requests/pull/6655",
            "https://github.com/psf/requests/commit/a58d7f2ffb4d00b46dca2d70a3932a0b37e22fac",
            "https://github.com/psf/requests",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/IYLSNK5TL46Q6XPRVMHVWS63MVJQOK4Q",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/N7WP6EYDSUOCOJYHDK5NX43PYZ4SNHGZ"
          ],
          "severity": "medium",
          "source_id": "GHSA-9wx4-h78v-vm56",
          "version": "2.31.0"
        }
      ]
    },
    {
      "name": "fake-useragent",
      "version": "1.4.0",
      "vulns": []
    },
    {
      "name": "cryptography",
      "version": "41.0.8",
      "vulns": [
        {
          "aliases": [
            "CGA-45f3-3fmq-7h5w",
            "CVE-2023-50782"
          ],
          "description": "Python Cryptography package vulnerable to Bleichenbacher timing oracle attack",
          "ecosystem": "python",
          "fix_versions": [
            "42.0.0"
          ],
          "id": "GHSA-3ww4-gg4f-jr7f",
          "package": "cryptography",
          "references": [
            "https://nvd.nist.gov/vuln/detail/CVE-2023-50782",
            "https://github.com/pyca/cryptography/issues/9785",
            "https://access.redhat.com/security/cve/CVE-2023-50782",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2254432",
            "https://github.com/pyca/cryptography"
          ],
          "severity": "high",
          "source_id": "GHSA-3ww4-gg4f-jr7f",
          "version": "41.0.8"
        },
        {
          "aliases": [
            "CGA-f4qg-9fw4-8247",
            "CVE-2024-26130",
            "PYSEC-2024-225"
          ],
          "description": "cryptography NULL pointer dereference with pkcs12.serialize_key_and_certificates when called with a non-matching certificate and private key and an hmac_hash override",
          "ecosystem": "python",
          "fix_versions": [
            "42.0.4"
          ],
          "id": "GHSA-6vqw-3v5j-54x4",
          "package": "cryptography",
          "references": [
            "https://github.com/pyca/cryptography/security/advisories/GHSA-6vqw-3v5j-54x4",
            "https://nvd.nist.gov/vuln/detail/CVE-2024-26130",
            "https://github.com/pyca/cryptography/pull/10423",
            "https://github.com/pyca/cryptography/commit/97d231672763cdb5959a3b191e692a362f1b9e55",
            "https://github.com/pyca/cryptography",
            "https://github.com/pypa/advisory-database/tree/main/vulns/cryptography/PYSEC-2024-225.yaml"
          ],
          "severity": "high",
          "source_id": "GHSA-6vqw-3v5j-54x4",
          "version": "41.0.8"
        },
        {
          "aliases": [
            "CGA-v739-9xhw-5vmf",
            "CVE-2024-0727"
          ],
          "description": "Null pointer dereference in PKCS12 parsing",
          "ecosystem": "python",
          "fix_versions": [
            "42.0.2"
          ],
          "id": "GHSA-9v9h-cgj8-h64p",
          "package": "cryptography",
          "references": [
            "https://nvd.nist.gov/vuln/detail/CVE-2024-0727",
            "https://github.com/github/advisory-database/pull/3472",
            "https://github.com/openssl/openssl/pull/23362",
            "https://github.com/alexcrichton/openssl-src-rs/commit/add20f73b6b42be7451af2e1044d4e0e778992b2",
            "https://github.com/openssl/openssl/commit/09df4395b5071217b76dc7d3d2e630eb8c5a79c2",
            "https://github.com/openssl/openssl/commit/775acfdbd0c6af9ac855f34969cdab0c0c90844a",
            "https://github.com/openssl/openssl/commit/d135eeab8a5dbf72b3da5240bab9ddb7678dbd2c",
            "https://github.com/pyca/cryptography/commit/3519591d255d4506fbcd0d04037d45271903c64d",
            "https://github.openssl.org/openssl/extended-releases/commit/03b3941d60c4bce58fab69a0c22377ab439bc0e8",
            "https://github.openssl.org/openssl/extended-releases/commit/aebaa5883e31122b404e450732dc833dc9dee539",
            "https://security.netapp.com/advisory/ntap-20240208-0006",
            "https://www.openssl.org/news/secadv/20240125.txt",
            "http://www.openwall.com/lists/oss-security/2024/03/11/1"
          ],
          "severity": "medium",
          "source_id": "GHSA-9v9h-cgj8-h64p",
          "version": "41.0.8"
        },
        {
          "aliases": [],
          "description": "pyca/cryptography has a vulnerable OpenSSL included in cryptography wheels",
          "ecosystem": "python",
          "fix_versions": [
            "43.0.1"
          ],
          "id": "GHSA-h4gh-qq45-vh27",
          "package": "cryptography",
          "references": [
            "https://github.com/pyca/cryptography/security/advisories/GHSA-h4gh-qq45-vh27",
            "https://github.com/pyca/cryptography",
            "https://openssl-library.org/news/secadv/20240903.txt"
          ],
          "severity": "medium",
          "source_id": "GHSA-h4gh-qq45-vh27",
          "version": "41.0.8"
        },
        {
          "aliases": [
            "CGA-f4qg-9fw4-8247",
            "CVE-2024-26130",
            "GHSA-6vqw-3v5j-54x4"
          ],
          "description": "cryptography is a package designed to expose cryptographic primitives and recipes to Python developers. Starting in version 38.0.0 and prior to version 42.0.4, if `pkcs12.serialize_key_and_certificates` is called with both a certificate whose public key did not match the provided private key and an `encryption_algorithm` with `hmac_hash` set (via `PrivateFormat.PKCS12.encryption_builder().hmac_hash(...)`, then a NULL pointer dereference would occur, crashing the Python process. This has been resolved in version 42.0.4, the first version in which a `ValueError` is properly raised.",
          "ecosystem": "python",
          "fix_versions": [
            "42.0.4",
            "97d231672763cdb5959a3b191e692a362f1b9e55"
          ],
          "id": "PYSEC-2024-225",
          "package": "cryptography",
          "references": [
            "https://github.com/pyca/cryptography/security/advisories/GHSA-6vqw-3v5j-54x4",
            "https://github.com/pyca/cryptography/commit/97d231672763cdb5959a3b191e692a362f1b9e55",
            "https://github.com/pyca/cryptography/pull/10423"
          ],
          "severity": "unknown",
          "source_id": "PYSEC-2024-225",
          "version": "41.0.8"
        }
      ]
    },
    {
      "name": "prometheus-client",
      "version": "0.19.0",
      "vulns": []
    },
    {
      "name": "structlog",
      "version": "23.2.0",
      "vulns": []
    },
    {
      "name": "python-dotenv",
      "version": "1.0.0",
      "vulns": []
    }
  ],
  "queries": [
    [
      "fastapi",
      "0.104.1"
    ],
    [
      "uvicorn",
      "0.24.0"
    ],
    [
      "pydantic",
      "2.5.0"
    ],
    [
      "httpx",
      "0.25.2"
    ],
    [
      "aiofiles",
      "23.2.1"
    ],
    [
      "python-multipart",
      "0.0.6"
    ],
    [
      "pysocks",
      "1.7.1"
    ],
    [
      "stem",
      "1.8.2"
    ],
    [
      "requests",
      "2.31.0"
    ],
    [
      "fake-useragent",
      "1.4.0"
    ],
    [
      "cryptography",
      "41.0.8"
    ],
    [
      "prometheus-client",
      "0.19.0"
    ],
    [
      "structlog",
      "23.2.0"
    ],
    [
      "python-dotenv",
      "1.0.0"
    ]
  ],
  "skipped": []
}
